SET TIME ZONE UTC;

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  user_name VARCHAR(50) NOT NULL UNIQUE,
  password VARCHAR(500) NOT NULL,
  email VARCHAR(255) NOT NULL,
  dev BOOLEAN DEFAULT FALSE
);
